<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>LycorisOni.Trader</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Library</OutputType>
        <Version>0.8.0</Version>
        <!-- The two lines below will set the output path for the binaries -->
        <OutputPath>bin\$(Configuration)\$(ProjectName)\$(AssemblyName)\</OutputPath>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SPTarkov.Common" Version="4.0.0" />
        <PackageReference Include="SPTarkov.DI" Version="4.0.0" />
        <PackageReference Include="SPTarkov.Server.Core" Version="4.0.0" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="WTT-ServerCommonLib">
            <HintPath>B:\DNspy Spt4.0 Development\SPT\user\mods\WTT-ServerCommonLib\WTT-ServerCommonLib.dll</HintPath>
            <Private>False</Private>
            <SpecificVersion>False</SpecificVersion>
        </Reference>
    </ItemGroup>
    <ItemGroup>
        <None Include="Data\**">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Folder Include="db\CustomQuests\**" />
        <Folder Include="ZoneData\**" />
    </ItemGroup>

</Project>
